name: 32. 🟢 kafka

on: workflow_dispatch

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: "github.com" # ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)

      - name: Setup Kafka
        uses: 280780363/kafka-action@v1.0
        with:
          kafka version: "latest" # Optional, kafka version
          zookeeper version: "latest" # Optional, zookeeper version
          kafka port: 9092 # Optional, kafka port
          zookeeper port: 2181 # Optional, zookeeper port
          auto create topic: "true" # Optional, auto create kafka topic

      - name: debug
        uses: wordsworth-mk/action-debug@main
        with:
            credentials: "user:password"

