name: 01. 🟢 app_baidu2douyin

on:
  # 当按计划（或按推/拉）触发具有输入的工作流时，所有输入值均为空，需要自己设置好默认值
  schedule:
    # 每天 08 点 30 分执行（时间 +8 就是北京时间）
    - cron: "30 00 * * *"

  workflow_dispatch:
    inputs:
      ARGS:
        description: |
          -n NUM, --num NUM
             发布 N 天的视频

          -d, --debug
             调试，会拷贝 mypy/tools 下的配置过来
        required: false
        type: string
        # 如果要传入整个字符串，需要用双引号括起来输入 "-m once"
        # 这种方式就像终端输入命令一样的
        default: "-d -n 1"

      # github action 还不支持复选框
      ENV_PUBLISH_PLATFORMS:
        type: string
        description: "选择发布平台，用 ',' 分割（不带空格，可选项: douyin,wechat,xiaohongshu）"
        required: false
        default: "douyin"

      ENV_PUBLISH_MOD:
        type: choice
        description: "选择发布时间模式"
        required: false
        default: "timing"
        options:
          - "now"
          - "timing"

      ENV_DOUYIN_PUBLISH_ACCOUNT:
        type: choice
        description: "选择抖音账号"
        required: false
        default: "middle"
        options:
          - "large" # 大号
          - "middle" # 中号
          - "test" # 测试账号

env:
  # 把 github action 的 input 设置到环境变量中
  ENV_PUBLISH_MOD: ${{ github.event.inputs.ENV_PUBLISH_MOD || 'timing' }}
  ENV_PUBLISH_PLATFORMS: ${{ github.event.inputs.ENV_PUBLISH_PLATFORMS || 'douyin' }}
  ENV_DOUYIN_PUBLISH_ACCOUNT: ${{ github.event.inputs.ENV_DOUYIN_PUBLISH_ACCOUNT || 'middle' }}

jobs:
  run_app:
    uses: wordsworth-mk/github-runner/.github/workflows/21.run.yml@main
    with:
      APP: baidu2douyin
      # 定时任务没办法给参数，只能在这里配置默认值了
      ARGS: ${{ inputs.ARGS || '-d -n 1' }}
    secrets:
      MYPY_ACCESS_TOKEN: ${{ secrets.MYPY_ACCESS_TOKEN }}
