name: 01. 🟢 app_baidu2douyin

on:
  # 当按计划（或按推/拉）触发具有输入的工作流时，所有输入值均为空，需要自己设置好默认值
  # schedule:
  #   # 时间 +8 就是北京时间
  #   - cron: "00 21 * * *"

  workflow_dispatch:
    inputs:
      ENV_PUBLISH_ACCOUNT:
        type: choice
        description: "选择账号"
        required: false
        default: "middle"
        # NOTICE: 与 const.py/Account 一一对应
        options:
          - "large" # 大号
          - "middle" # 中号
          - "test" # 测试账号

      ARGS:
        description: |
          -n NUM, --num NUM
             发布 N 天的视频

          -d, --debug
             调试，会拷贝 tools 下的 cookies 过来
        required: false
        type: string
        # 如果要传入整个字符串，需要用双引号括起来输入 "-m once"
        # 这种方式就像终端输入命令一样的
        default: "-d -n 1"

      ENV_BAIDU_AIGC_TYPE:
        type: choice
        # NOTICE: 定义在 const.py/FILE_TYPE_PPT
        description: "AI 生成内容类型"
        required: false
        default: "doc"
        options:
          - "ppt"
          - "doc"
          - "random"

      ENV_PUBLISH_MEDIA_TYPE:
        type: choice
        # NOTICE: 定义在 const.py/MEDIA_TYPE_IMG_ARTICLE
        description: "发布媒体类型"
        required: false
        default: "image_article"
        options:
          - "video" # 视频
          - "image_article" # 图文
          - "random"

      ENV_BAIDU_AIGC_TOPIC:
        type: string
        description: "发布内容的主题"
        required: false
        default: ""

      # github action 还不支持复选框
      ENV_PUBLISH_PLATFORMS:
        type: string
        description: "选择发布平台，用 ',' 分割（不带空格，可选项: douyin,weixin,xiaohongshu）"
        required: false
        default: "douyin"

      ENV_PUBLISH_MOD:
        type: choice
        description: "选择发布时间模式"
        required: false
        default: "timing"
        options:
          - "now"
          - "timing"

jobs:
  run_app:
    uses: wordsworth-mk/github-runner/.github/workflows/21.run.yml@main
    with:
      # 无法通过调用方定义环境变量，只能通过 with 传递 input 参数进去了
      # 注意，新增变量的话，需要在 run.yaml 中进行定义
      ENV_PUBLISH_MOD: ${{ github.event.inputs.ENV_PUBLISH_MOD }}
      ENV_PUBLISH_PLATFORMS: ${{ github.event.inputs.ENV_PUBLISH_PLATFORMS }}
      ENV_PUBLISH_MEDIA_TYPE: ${{ github.event.inputs.ENV_PUBLISH_MEDIA_TYPE }}
      ENV_PUBLISH_ACCOUNT: ${{ github.event.inputs.ENV_PUBLISH_ACCOUNT }}
      ENV_BAIDU_AIGC_TYPE: ${{ github.event.inputs.ENV_BAIDU_AIGC_TYPE }}
      ENV_BAIDU_AIGC_TOPIC: ${{ github.event.inputs.ENV_BAIDU_AIGC_TOPIC }}

      APP: baidu2douyin
      # 定时任务没办法给参数，只能在这里配置默认值了
      ARGS: ${{ inputs.ARGS || '-d -n 1' }}

    secrets:
      MYPY_ACCESS_TOKEN: ${{ secrets.MYPY_ACCESS_TOKEN }}
