name: 03. 🟢 app_tiktok2douyin

on:
  workflow_dispatch:
    inputs:
      ARGS:
        description: |
          -u https://xxx
        required: false
        type: string
        default: "-u "

      REF:
        description: "分支或标签、提交ID"
        type: choice
        required: false
        options:
          - "master"
          - "release"

      # github action 还不支持复选框
      ENV_PUBLISH_PLATFORMS:
        type: string
        description: "选择发布平台，用 ',' 分割（不带空格，可选项: douyin,wechat,xiaohongshu）"
        required: false
        default: "douyin"

      ENV_PUBLISH_MOD:
        type: choice
        description: "选择发布时间模式"
        required: false
        default: "timing"
        options:
          - "now"
          - "timing"

      ENV_PUBLISH_ACCOUNT:
        type: choice
        description: "选择账号"
        required: false
        default: "test"
        options:
          - "large" # 大号
          - "middle" # 中号
          - "test" # 测试账号

jobs:
  run:
    uses: wordsworth-mk/github-runner/.github/workflows/21.run.yml@main
    with:
      # 环境变量
      ENV_PUBLISH_MOD: ${{ github.event.inputs.ENV_PUBLISH_MOD }}
      ENV_PUBLISH_PLATFORMS: ${{ github.event.inputs.ENV_PUBLISH_PLATFORMS }}
      ENV_PUBLISH_ACCOUNT: ${{ github.event.inputs.ENV_PUBLISH_ACCOUNT }}

      APP: tiktok2douyin
      # 定时执行没传这个值也可以，在 run.yml 已经做了处理了
      ARGS: ${{ inputs.ARGS }}
      DEPENDENT_BINARY: "ffmpeg"
      REF: ${{ inputs.REF }}
    secrets:
      MYPY_ACCESS_TOKEN: ${{ secrets.MYPY_ACCESS_TOKEN }}
