name: 04. 🕢 app_work_schedule

on:
  workflow_dispatch:
    inputs:
      ARGS:
        description: "排班参数用逗号分隔: 0 表示休息, 1 表示上班, 2 表示夜班, 3 表示备班, 4 表示备班二"
        required: false
        type: string
        default: ""

  # 定时执行
  schedule:
    # 代表国际标准时间，实际北京时间需要 +8 小时
    - cron: "00 13 * * *"

jobs:
  run:
    uses: wordsworth-mk/github-runner/.github/workflows/run.yml@main
    with:
      APP: qlx_work_schedules
      ARGS: ${{ inputs.ARGS }}
      SIMPLE_RUN: true
    secrets:
      MYPY_ACCESS_TOKEN: ${{ secrets.MYPY_ACCESS_TOKEN }}
