name: 07. 🟢 app_auto_course

on:
  workflow_dispatch:
    inputs:
      COURSE_URL:
        description: "课程地址"
        required: true
        type: string

      LOGIN_NAME:
        description: "登录账号"
        required: true
        type: string

      LOGIN_PWD:
        description: "登录密码"
        required: true
        type: string

      PLATFORM:
        description: "学习平台"
        required: true
        default: "huayi"
        type: choice
        options:
          - "huayi"
          - "haoyisheng"

      MISSION_BATCH_MODE:
        description: "课件学习模式"
        type: choice
        # 在 mypy/apps/auto_course/main.py 下定义
        default: "one_by_one"
        required: true
        options:
          - "one_by_one"
          - "multi"

      LOGIN_TYPE:
        description: "登录账号类型"
        type: choice
        default: "1"
        required: true
        options:
          - "1" # 用户名
          - "3" # 邮箱
          - "4" # 身份证

      REF:
        description: "Python 仓库分支或标签、提交ID"
        type: string
        required: false
        default: "master"

  # 该事件可以通过 API 触发
  repository_dispatch:
    types:
      - app_auto_course

jobs:
  run_app:
    uses: wordsworth-mk/github-runner/.github/workflows/21.run.yml@main
    with:
      APP: auto_course
      WITH_3PARTY: false
      ARGS: >-
        -u "${{ inputs.COURSE_URL || github.event.client_payload.COURSE_URL }}"
        -t ${{ inputs.LOGIN_TYPE || github.event.client_payload.LOGIN_TYPE }}
        -a ${{ inputs.LOGIN_NAME || github.event.client_payload.LOGIN_NAME }}
        -p ${{ inputs.LOGIN_PWD || github.event.client_payload.LOGIN_PWD }}
        -m ${{ inputs.MISSION_BATCH_MODE || github.event.client_payload.MISSION_BATCH_MODE }}
        -f ${{ inputs.PLATFORM || github.event.client_payload.PLATFORM || 'huayi' }}
      REF: ${{ inputs.REF || github.event.client_payload.REF }}
      COMMIT_CHANGE: false

    secrets:
      MYPY_ACCESS_TOKEN: ${{ secrets.MYPY_ACCESS_TOKEN }}
