name: 07. 🟢 app_auto_course

on:
  workflow_dispatch:
    inputs:
      ARGS:
        description: |
          -u, --url 课程地址
        required: false
        type: string
        default: "-u "

      DEBUG:
        description: "支持连接到虚拟机进行调试"
        type: boolean
        required: false
        default: false

      REF:
        description: "分支或标签、提交ID"
        type: choice
        required: false
        options:
          - "master"
          - "release"

  # 该事件可以通过 API 触发
  repository_dispatch:
    types:
      - app_auto_course

jobs:
  run_app:
    uses: wordsworth-mk/github-runner/.github/workflows/21.run.yml@main
    with:
      APP: auto_course
      WITH_3PARTY: false
      ARGS: ${{ inputs.ARGS || github.event.client_payload.ARGS }}
      DEBUG: ${{ inputs.DEBUG || false }}
      REF: ${{ inputs.REF || 'master' }}

    secrets:
      MYPY_ACCESS_TOKEN: ${{ secrets.MYPY_ACCESS_TOKEN }}
