name: 07. 🟢 app_auto_course

on:
  workflow_dispatch:
    inputs:
      ARGS:
        description: |
          -u, --url 课程地址
        required: false
        type: string
        default: "-u "

jobs:
  run_app:
    uses: wordsworth-mk/github-runner/.github/workflows/21.run.yml@main
    with:
      APP: auto_course
      WITH_3PARTY: false
      ARGS: ${{ inputs.ARGS || '-u ' }}

    secrets:
      MYPY_ACCESS_TOKEN: ${{ secrets.MYPY_ACCESS_TOKEN }}
