name: 09. 🟢 app_quant

on:
  # 使用 cron 定时执行
  schedule:
    - cron: "30 1 * * *"

  workflow_dispatch:
    inputs:
      MODULE:
        description: "运行模块"
        default: "monitor"
        required: false
        type: choice
        options:
          - "monitor"


jobs:
  run_app:
    uses: wordsworth-mk/github-runner/.github/workflows/21.run.yml@main
    with:
      APP: quant
      WITH_3PARTY: false
      ARGS: >-
        --module ${{ inputs.MODULE || github.event.client_payload.MODULE || monitor }}
      COMMIT_CHANGE: false
      DEPENDENT_BINARY: ""

    secrets:
      MYPY_ACCESS_TOKEN: ${{ secrets.MYPY_ACCESS_TOKEN }}
