name: 22. 📦 打包发布

on:
  workflow_dispatch:
    inputs:
      DO_RELEASE:
        description: "是否创建标签及发行版"
        type: boolean
        required: false
        default: false

      APP_DIR:
        description: "打包的 app 名称"
        type: choice
        required: false
        default: "apps/baidu2douyin"
        options:
          - "apps/baidu2douyin"
          - "tools/get_cookies.py"
          - "tools/launch_browser.py"

  workflow_call:
    inputs:
      DO_RELEASE:
        description: "是否创建标签及发行版"
        type: boolean
        required: false
        default: false

    secrets:
      MYPY_ACCESS_TOKEN:
        required: false

env:
  APP_BASE_PATH: mypy/apps
  BUILD_TOOL: mypy/build/build.sh
  ENV_INIT_SCRIPT: mypy/env_init.sh
  # 打包后的 APP 可执行文件的存放路径
  PKG_ZIP_PATH: mypy/build/_pkg.zip
  BUILD_PKG_PATH: mypy/build/_pkg/

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.9"]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        # 访问仓库用到的 Personal access token
        env:
          MYPY_ACCESS_TOKEN: ${{ secrets.MYPY_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
        with:
          token: ${{ env.MYPY_ACCESS_TOKEN }}
          repository: M-Kepler/Python

      - name: 设置 Python ${{ matrix.python-version }} 环境
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: 安装依赖程序
        continue-on-error: true
        uses: ConorMacBride/install-package@v1.1.0
        with:
          apt: ${{ inputs.DEPENDENT_BINARY }}
          choco: ${{ inputs.DEPENDENT_BINARY }}

      # - name: 安装字体
      #   run: |
      #     bash mypy/build/install_font.sh ${{ env.FONT_DIR }}

      - name: 初始化运行环境
        run: |
          bash ${{ env.ENV_INIT_SCRIPT }}
        env:
          LC_ALL: C.UTF-8
          LANG: C.UTF-8
        # windows 版支持用 gitbash 执行命令
        shell: bash

      - name: 打包
        run: |
          if [ ! -z "${{ inputs.APP_DIR }}" ]; then
            bash ${{ env.BUILD_TOOL }} mypy/${{ inputs.APP_DIR }}
          else
            for app in ${{ env.APP_BASE_PATH }}; do
              bash ${{ env.BUILD_TOOL }} $app
            done
          fi

        env:
          LC_ALL: C.UTF-8
          LANG: C.UTF-8
        shell: bash

      - name: zip 打包产物
        uses: vimtor/action-zip@v1.2
        with:
          files: ${{ env.BUILD_PKG_PATH }}
          dest: ${{ env.PKG_ZIP_PATH }}

      - name: 设置时区
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"

      - name: 获取当前日期
        id: date
        run: |
          echo $(date +'%Y%m%d-%H%M%S')
          echo "date=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
        shell: bash

      - name: 更新 CHANGELLOG
        if: ${{ inputs.DO_RELEASE }}
        uses: saadmk11/changelog-ci@v1.1.2

      - name: 创建 github Tag
        id: create_release
        if: ${{ inputs.DO_RELEASE }}
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}-${{ steps.date.outputs.date }}
          name: release-${{ github.ref_name }}-${{ steps.date.outputs.date }}
          draft: false
          prerelease: false

      - name: 上传 Release
        id: upload-release-asset
        if: ${{ inputs.DO_RELEASE }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/${{ env.PKG_ZIP_PATH }}
          asset_name: pkg.zip
          asset_content_type: application/zip

      # Github actions Artifact 可以用来存储 action 生产出来的产物
      # 当你上传成功后，后续的流程就可以下载这些文件来使用
      - name: 上传 Artifact
        if: ${{ inputs.DO_RELEASE }}
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.os }} Build
          path: |
            ${{ env.PKG_ZIP_PATH }}
