name: 31. 🟢 kind

on: workflow_dispatch

env:
  KIND_BASE_PATH: ./docker-compose/00.kind

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: "github.com" # ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)

      - name: 设置运行环境配置
        run: |
          export ENABLE_K8S_TOOL=1
          git clone git@github.com:M-Kepler/dotfiles ~/dotfiles
          cd ~/dotfiles
          bash run.sh
          # 创建个脚本，继续执行后续流水线
          echo "touch $GITHUB_WORKSPACE/continue" > ~/quit_ssh
          chmod a+x ~/quit_ssh

      - name: 拉取代码
        run: |
          git clone git@github.com:M-Kepler/docker-compose
          ls -al ./docker-compose/

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
          config: ${{env.KIND_BASE_PATH}}/kind-3nodes.yaml
          cluster_name: test

      - name: debug
        uses: wordsworth-mk/action-debug@main
        with:
          credentials: "user:password"
