# https://zhuanlan.zhihu.com/p/387389708?utm_id=0

# XXX 40分钟左右会自动断开

name: 90. 🚧 ssh_by_ngrok

on:
  workflow_dispatch:

jobs:
  SSH:
    runs-on: ubuntu-latest
    steps:
      # 需要在仓库中设置 NGROK_TOKEN 和 USER_PASS
      - name: Debug via SSH
        uses: luchihoratiu/debug-via-ssh@v1.2
        with:
            # NGROK 凭证
            NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
            # 用于 SSH 登录
            SSH_PASS: ${{ secrets.USER_PASS }}
