name: 99. action-test

on:
  workflow_dispatch:
    inputs:
      SSH_WITH_VSCODE:
        type: boolean
        description: "用 vscode 连接远程"
        required: false
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 测试
        run: |
          echo "hello world"
