name: aaaa

on:
  workflow_dispatch:
    inputs:
      SYSTEM:
        type: choice
        description: "系统"
        required: false
        options:
          - Ubuntu
          - Windows


jobs:
  new_ssh_keep_connect:
    runs-on: windows-latest
    steps:

      ##################################################
      # https://stackoverflow.com/questions/75578151/how-do-i-clone-a-repo-in-b-repo-github-actions-if-two-repo-is-in-same-organizati
      # NOTICE: 也可以手动在 github actions 里拉取，不过要用 https 协议，而且提交的时候需要进行账密认证
      # 而通过以下方式这不需要账密认证

      - uses: fawazahmed0/action-debug@main
        with:
          credentials: "user:password"
