name: xxx_Package Application with Pyinstaller

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: test
      run: |
        ls -al

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
    - uses: actions/upload-artifact@v2
      with:
        name: name-of-artifact
        path: src/dist/windows