name: 🟢 流水线功能测试

on:
  # 该事件可以通过 API 触发
  repository_dispatch:
    types:
      - mypy_event_type.test_app

  # 手动触发时输入参数
  workflow_dispatch:
    inputs:
      ARGS:
        description: "排班参数用逗号分隔: 0 表示休息 1 表示上班 2 表示夜班 3 表示备班"
        required: false
        type: string
        default: ""
      SIMPLE_RUN:
        description: "是否简单运行（不安装程序依赖和字体）"
        type: boolean
        required: false
        default: true
      DOUYIN_ACCOUNT:
        type: choice
        description: "选择抖音账号"
        required: true
        default: "大号"
        options: ["大号", "中号"]

env:
  ENV: test
  APP_BASE_PATH: mypy/apps

jobs:
  # 单元测试
  # unittest_and_coverage:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Check timezone
  #       run: |
  #         date

  #     - name: Set timezone
  #       uses: szenius/set-timezone@v1.2
  #       with:
  #         timezoneLinux: "Asia/Singapore"
  #         timezoneMacos: "Asia/Singapore"
  #         timezoneWindows: "Asia/Singapore"

  #     - name: Check timezone after set-timezone
  #       run: |
  #         date

  # 打包
  # package:
  #   needs:
  #     - unittest_and_coverage
  #   uses: M-Kepler/Python/.github/workflows/package.yml@master
  #   with:
  #     APPS_PATH: mypy/apps # ${{ env.APP_BASE_PATH }}

  run:
    # NOTICE: 如果您是通过 repository_dispatch 触发工作流，需要使用 github.event.client_payload.[参数] 来传递参数
    - uses: wordsworth-mk/github-runner/.github/workflows/run.yml@main
      with:
        APP: test_app
        ARGS: ${{ inputs.ARGS || github.event.client_payload.ARGS }}
        SIMPLE_RUN: ${{ inputs.SIMPLE_RUN || github.event.client_payload.SIMPLE_RUN }}
        COMMIT_CHANGE: ${{ inputs.COMMIT_CHANGE || github.event.client_payload.COMMIT_CHANGE }}

    - name: sleep
      run: |
        sleep 10000

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        detached: true
