name: 🟢 app_baidu2douyin

on:
  workflow_dispatch:
    inputs:
      ARGS:
        description: |
          -m auto 表示自动模式，不需要确认 AI 生成的主题
          -n 2 表示生成 PPT 数量
        required: false
        type: string
        # 如果要传入整个字符串，需要用双引号括起来输入 "-m once"
        # 这种方式就像终端输入命令一样的
        default: "-m auto -n 2"

jobs:
  run:
    uses: wordsworth-mk/github-runner/.github/workflows/run.yml@main
    with:
      APP: baidu2douyin
      ARGS: ${{ inputs.ARGS }}
      DEPENDENT_BINARY: "ffmpeg"
