name: 🟢 app_baidu2douyin

on:
  workflow_dispatch:
    inputs:
      ARGS:
        description: |
          -m {auto,manual}, --mode {auto,manual}
             运行模式, -m auto 表示自动运行; -m manural 表示交互模式

          -n NUM, --num NUM
             发布 N 天的视频

          -d, --debug
             调试，会拷贝 mypy/tools 下的配置过来
        required: false
        type: string
        # 如果要传入整个字符串，需要用双引号括起来输入 "-m once"
        # 这种方式就像终端输入命令一样的
        default: "-n 2 -d"

      ENV_TO_PLATFORMS:
        type: string
        description: "选择发布平台，用 ',' 分割（不带空格，可选项: douyin,wechat,xiaohongshu）"
        required: false
        default: "douyin,wechat"

      ENV_PUBLISH_MOD:
        type: choice
        description: "选择发布时间模式"
        required: false
        default: "timing"
        potions:
          - "now"
          - "timing"

  schedule:
    # 每个月 1 号和 15 号执行
    - cron: "30 13 1,15 * *"

env:
  ENV_TO_PLATFORMS: ${{ github.event.inputs.ENV_TO_PLATFORMS }}
  ENV_DOUYIN_ACCOUNT: ${{ github.event.inputs.ENV_DOUYIN_ACCOUNT }}

jobs:
  run_app:
    uses: wordsworth-mk/github-runner/.github/workflows/run.yml@main
    with:
      APP: baidu2douyin
      ARGS: ${{ inputs.ARGS }}
    secrets:
      MYPY_ACCESS_TOKEN: ${{ secrets.MYPY_ACCESS_TOKEN }}
