name: 🟢 app_youtu2douyin

on:
  workflow_dispatch:
    inputs:
      DOUYIN_ACCOUNT:
        type: choice
        description: "选择抖音账号"
        required: true
        default: "大号"
        options: ["大号", "中号"]

      ARGS:
        description: |
          -m {loop,once,manual}
             运行模式, -m loop 表示持续监控; -m once 表示运行一次; -m manual 表示手动触发

          -t {channel,playlist}
             视频合集类型(channel/playlist)

          --publish
            执行发布操作（默认发布）

          --no-publish
            不执行发布操作

          -f
            不管是否已经发布过，都强制发布该视频

        required: false
        type: string
        # 如果要传入整个字符串，需要用双引号括起来输入 "-m once"
        # 这种方式就像终端输入命令一样的
        default: "-m manual "

  # 定时执行
  schedule:
    # 代表国际标准时间，实际北京时间需要 +8 小时
    - cron: "30 13 * * *"

jobs:
  run:
    uses: wordsworth-mk/github-runner/.github/workflows/run.yml@main
    with:
      APP: youtu2douyin
      # 定时执行没传这个值也可以，在 run.yml 已经做了处理了
      ARGS: ${{ inputs.ARGS }}
      DEPENDENT_BINARY: "ffmpeg"
      FORCE_COMMIT: true
    secrets:
      MYPY_ACCESS_TOKEN: ${{ secrets.MYPY_ACCESS_TOKEN }}
