name: 🟢 app_baidu2douyin

on:
  workflow_dispatch:
    inputs:
      ARGS:
        description: |
          -m {auto,manual}, --mode {auto,manual}
             运行模式, -m auto 表示自动运行; -m manural 表示交互模式

          -n NUM, --num NUM
             发布 N 天的视频

          -d, --debug
             调试，会拷贝 mypy/tools 下的配置过来
        required: false
        type: string
        # 如果要传入整个字符串，需要用双引号括起来输入 "-m once"
        # 这种方式就像终端输入命令一样的
        default: "-n 2 -d"
  schedule:
    # 每个月 1 号和 15 号执行
    - cron: "30 13 1,15 * *"

jobs:
  run:
    uses: wordsworth-mk/github-runner/.github/workflows/run.yml@main
    env:
      IN_GITHUBACTION: true
    with:
      APP: baidu2douyin
      ARGS: ${{ inputs.ARGS }}
    secrets:
      MYPY_ACCESS_TOKEN: ${{ secrets.MYPY_ACCESS_TOKEN }}
