name: 🟢 app_baidu2douyin

on:
  schedule:
    # 每个月 1 号和 15 号的 21 点 30 分执行
    - cron: "30 13 1,15 * *"

  workflow_dispatch:
    inputs:
      ARGS:
        description: |
          -m {auto,manual}, --mode {auto,manual}
             运行模式, -m auto 表示自动运行; -m manural 表示交互模式

          -n NUM, --num NUM
             发布 N 天的视频

          -d, --debug
             调试，会拷贝 mypy/tools 下的配置过来
        required: false
        type: string
        # 如果要传入整个字符串，需要用双引号括起来输入 "-m once"
        # 这种方式就像终端输入命令一样的
        default: "-d -n 1"

      # github action 还不支持复选框
      ENV_PUBLISH_PLATFORMS:
        type: string
        description: "选择发布平台，用 ',' 分割（不带空格，可选项: douyin,wechat,xiaohongshu）"
        required: false
        default: "douyin,wechat"

      ENV_PUBLISH_MOD:
        type: choice
        description: "选择发布时间模式"
        required: false
        default: "timing"
        options:
          - "now"
          - "timing"

      ENV_DOUYIN_PUBLISH_ACCOUNT:
        type: choice
        description: "选择抖音账号"
        required: false
        default: "large"
        options:
          - "large" # 大号
          - "middle" # 中号
          - "test" # 测试账号

env:
  # 把 github action 的 input 设置到环境变量中
  ENV_PUBLISH_MOD: ${{ github.event.inputs.ENV_PUBLISH_MOD }}
  ENV_PUBLISH_PLATFORMS: ${{ github.event.inputs.ENV_PUBLISH_PLATFORMS }}
  ENV_DOUYIN_PUBLISH_ACCOUNT: ${{ github.event.inputs.ENV_DOUYIN_PUBLISH_ACCOUNT }}

jobs:
  run_app:
    uses: wordsworth-mk/github-runner/.github/workflows/run.yml@main
    with:
      APP: baidu2douyin
      ARGS: ${{ inputs.ARGS }}
    secrets:
      MYPY_ACCESS_TOKEN: ${{ secrets.MYPY_ACCESS_TOKEN }}
