name: 🟢 kind

on: workflow_dispatch

env:
  KIND_BASE_PATH: ./docker-compose/00.kind

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: "github.com" # ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)

      - name: test
        run: |
          git clone git@github.com:M-Kepler/docker-compose
          git clone git@github.com:M-Kepler/dotfiles
          ls -al

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
          config: ${{env.KIND_BASE_PATH}}/kind-3nodes.yaml
          cluster_name: test

      - name: deploy simpleweb
        run: |
          bash ${{env.KIND_BASE_PATH}}/demo/simpleweb/tools/deploy_with_kubectl.sh

      - name: test
        run: |
          kubectl get ns
