name: 📦️ 打包发布

on:
  workflow_call:
    inputs:
      APPS_PATH:
        required: true
        type: string
      PKG_DIR_PATH:
        required: false
        type: string
        default: mypy/pkg/

env:
  ENV_INIT_SCRIPT: mypy/env_init.sh

jobs:
  build:
    env:
      PYTHON_VERSION: 3.8

    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Package
        uses: ConorMacBride/install-package@v1.1.0
        with:
          apt: ffmpeg unoconv libreoffice poppler-utils

      - name: Set up python environment
        run: |
          bash ${{ env.ENV_INIT_SCRIPT }}

      - name: Build Executable
        run: |
          for app in $(ls ${{ inputs.APPS_PATH }}); do
              bash mypy/build/build.sh mypy/apps/$app
          done

      # Github actions Artifact 可以用来存储 action 生产出来的产物
      # 当你上传成功后，后续的流程就可以下载这些文件来使用
      # 上传工件 OK
      # - name: Upload a Build Artifact
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: ${{ runner.os }} Build
      #     path: |
      #       ${{ inputs.PKG_DIR_PATH }}

      # 创建发行版 OK
      # - name: Create Release
      #   id: create_release
      #   uses: softprops/action-gh-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref_name }}
      #     name: Release ${{ github.ref_name }}
      #     draft: false
      #     prerelease: false
