name: example-ngrok-kind-v2
on:
  workflow_dispatch:

jobs:
  example-ngrok-kind-v2:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1

      - uses: shaowenchen/debugger-action@v2
        name: debugger
        timeout-minutes: 300000000
        continue-on-error: true
        with:
          ngrok_token: ${{ secrets.NGROK_TOKEN }}
