# https://zhuanlan.zhihu.com/p/387389708?utm_id=0
# https://github.com/marketplace/actions/debugging-with-tmate
# https://github.com/marketplace/actions/debugging-with-ssh

name: 🍉 ssh_keep_connect

on:
  workflow_dispatch:
    inputs:
      SIMPLE_RUN:
        type: boolean
        description: "单纯起个 SSH"
        required: false
        default: false

env:
  FONT_DIR: mypy/assets/font
  ENV_INIT_SCRIPT: mypy/env_init.sh
  DEPENDENT_BINARY: "ffmpeg unoconv libreoffice poppler-utils"
  PYTHON_VERSION: 3.9

jobs:
  new_ssh_keep_connect:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        if: ${{ ! inputs.SIMPLE_RUN }}
        uses: actions/checkout@v4
        env:
          MYPY_ACCESS_TOKEN: ${{ secrets.MYPY_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
        with:
          token: ${{ env.MYPY_ACCESS_TOKEN }}
          repository: M-Kepler/Python

      - name: 设置时区
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: "github.com" # ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)

      - name: 拉取代码
        run: |
          git clone git@github.com:M-Kepler/dotfiles ~/dotfiles

      - name: 设置运行环境配置
        run: |
          cd ~/dotfiles
          export MSYSTEM=1
          bash run.sh
          source ~/.bashrc

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 安装依赖程序
        if: ${{ ! inputs.SIMPLE_RUN }}
        uses: ConorMacBride/install-package@v1.1.0
        with:
          apt: ${{ env.DEPENDENT_BINARY }}

      - name: 安装字体
        if: ${{ ! inputs.SIMPLE_RUN }}
        run: |
          bash mypy/build/install_font.sh ${{ env.FONT_DIR }}

      - name: 初始化运行环境
        if: ${{ ! inputs.SIMPLE_RUN }}
        run: |
          bash ${{ env.ENV_INIT_SCRIPT }}

      # 删掉一些预装的软件，
      - name: 清理磁盘
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /etc/mysql /etc/php
          sudo -E apt-get -y purge azure-cli* docker* ghc* zulu* hhvm* llvm* firefox* google* dotnet* aspnetcore* powershell* openjdk* adoptopenjdk* mysql* php* mongodb* moby* snap* || true
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install libfuse-dev $(curl -fsSL git.io/depends-ubuntu-2204)
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean

      - name: 安装第三方服务
        if: ${{ ! inputs.SIMPLE_RUN }}
        continue-on-error: true # 即使失败了也继续后续流程
        run: |
          bash mypy/3party/init.sh

      ##################################################
      # 从这里开始是对服务器的配置
      ##################################################
      # https://stackoverflow.com/questions/75578151/how-do-i-clone-a-repo-in-b-repo-github-actions-if-two-repo-is-in-same-organizati
      # NOTICE: 也可以手动在 github actions 里拉取，不过要用 https 协议，而且提交的时候需要进行账密认证
      # 而通过以下方式这不需要账密认证

      - name: 配置 git 账号
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions-user@github.com"
          git config --global --list

      # - name: 设置 Bash
      #   run: |
      #     cat << EOF >> ~/.bashrc
      #     set -o vi
      #     bind -m vi-insert '\c-l':clear-screen
      #     alias ..="cd .."
      #     alias ll='ls -l'
      #     alias la='ls -A'
      #     alias g='git'
      #     alias cls='clear'
      #     export PS1="\[\e[1;32m\]\u@\h\[\e[0m\]:\[\e[1;34m\]\w\[\e[0m\]\$ "
      #     EOF
      #     # 连接后再执行才有用
      #     source ~/.bashrc

      - uses: fawazahmed0/action-debug@main
        with:
            credentials: "user:password"
