name: 🚥 代码质量检查

on:
  workflow_call:
    inputs:
      BASE_PATH:
        required: true
        type: string

    # 外部调用的时候提供 token 用来拉取本私有仓库
    secrets:
      MYPY_ACCESS_TOKEN:
        required: false

jobs:
  # 代码质量
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # 访问仓库用到的 Personal access token
        env:
          MYPY_ACCESS_TOKEN: ${{ secrets.MYPY_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
        with:
          token: ${{ env.MYPY_ACCESS_TOKEN }}
          repository: M-Kepler/Python

      - name: Flake8 检查
        run: |
          pip install flake8 > /dev/null 2>&1
          flake8 --config .flake8 ${{ inputs.BASE_PATH }}
          [ $? == 0 ] && echo "flake8 success"

      - name: Pylint 检查
        continue-on-error: true # 即使失败了也继续后续流程
        run: |
          pip install pylint > /dev/null 2>&1
          # pylint 命令执行返回码非 0 的话，后面的命令不会被执行的
          pylint --rcfile .pylintrc ${{ inputs.BASE_PATH }} -r y || true
          # 不论 pylint 结果如何，始终是 0
          # pylint_ret=$?
