name: 🚥 代码质量检查

on:
  workflow_call:
    inputs:
      APP_PATH:
        required: true
        type: string

jobs:
  # 代码质量
  python_code_quality_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Flake8 check
        run: |
          pip install flake8 > /dev/null 2>&1
          flake8 --config .flake8 ${{ inputs.APP_PATH }}
          [ $? == 0 ] && echo "flake8 success"

      - name: Pylint check
        continue-on-error: true # 即使失败了也继续后续流程
        run: |
          pip install pylint > /dev/null 2>&1
          # pylint 命令执行返回码非 0 的话，后面的命令不会被执行的
          pylint --rcfile .pylintrc ${{ inputs.APP_PATH }} -r y || true
          # 不论 pylint 结果如何，始终是 0
          # pylint_ret=$?
