name: __test_create_cluster_by_kind

on: workflow_dispatch

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1

      - name: test
        run: |
          kubectl get nodes

