name: test-ssh

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/orgs/community/discussions/64820
      # 保存你的 deploy key 这样进入终端后才可以 clone 其他仓库的代码
      - name: setup git
        run: |
          ssh-agent bash
          ssh-add ~/.ssh/id_rsa <<< ${{secrets.MYPY_ACCESS_TOKEN}}
          git clone git@github.com:StanCodes/$reponame.git

      # 会卡在这里等待链接，默认 15 分钟
      # 可以在连接后通过 `touch /tmp/keepalive` 保持连接
      # - name: 创建 SSH 会话
      #   uses: csexton/debugger-action@master
      - uses: fawazahmed0/action-debug@main
        with:
            credentials: "user:password"
